### ISSUE TITLE
Failure to build in a unikernel with target hvt

### ISSUE THREAD

**Issue by Armael** [mirage/mirage-crypto#180] opened 2023-07-01 20:52 UTC
I hope this is the right place to report this.
I just tried to build the `device-usage/conduit_server` unikernel in mirage-skeleton, with target `hvt`:

```
git clone https://github.com/mirage/mirage-skeleton
cd mirage-skeleton/device-usage/conduit_server
mirage configure -t hvt
make depend
make
```

(`mirage --version` is `v4.4.0`)

This last build step fails with errors in mirage-crypto (see link below). I can install mirage-crypto as a normal opam library in my standard switch without problems, so I suspect the failure is related to cross-compilation / the monorepo setup?

the build errors: https://gist.github.com/Armael/587bdbfadab6a9a34e5aeba43731fb37
(`current` is the name of my global opam switch in which the mirage package is installed, in case that helps)

**Comment by Armael** [comment] 2023-07-01 21:09
Hm, the build worked after creating a fresh global opam switch.
So I guess this is in fact not related to mirage-crypto, and more a glitch of the mirage tool... Should I move the issue to mirage/mirage?

**Comment by hannesm** [comment] 2023-07-03 09:49
I don't understand what causes the error. :/ So, I'm not sure where to report it... It's great that it works after creating a fresh opam switch for you, though :)

**Comment by hannesm** [comment] 2023-07-31 21:05
Since I neither understand the issue, nor can reproduce, I'll close this. If you encounter such issues again, please report at the mirage or opam-monorepo repository.

**Closed by hannesm** 2023-07-31 21:05 UTC
